//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyriller.Checker.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordType
    {
        public WordType()
        {
            this.Words = new HashSet<Word>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string SysName { get; set; }
        public int SpeechPartID { get; set; }
        public int OrderNumber { get; set; }
        public string Comments { get; set; }
    
        public virtual ICollection<Word> Words { get; set; }
    }
}
