//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyriller.Tests.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CyrillerEntities : DbContext
    {
        public CyrillerEntities()
            : base("name=CyrillerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdjectiveDictionary> AdjectiveDictionaries { get; set; }
        public virtual DbSet<AdjectiveRule> AdjectiveRules { get; set; }
        public virtual DbSet<Animate> Animates { get; set; }
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<NounDictionary> NounDictionaries { get; set; }
        public virtual DbSet<NounRule> NounRules { get; set; }
        public virtual DbSet<Number> Numbers { get; set; }
        public virtual DbSet<RawWord> RawWords { get; set; }
        public virtual DbSet<SpeechPart> SpeechParts { get; set; }
        public virtual DbSet<WordCase> WordCases { get; set; }
        public virtual DbSet<Word> Words { get; set; }
        public virtual DbSet<WordType> WordTypes { get; set; }
    }
}
