//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyriller.Tests.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawWord
    {
        public int ID { get; set; }
        public int LemmaID { get; set; }
        public string Name { get; set; }
        public Nullable<int> SpeechPartID { get; set; }
        public string Xml { get; set; }
    
        public virtual SpeechPart SpeechPart { get; set; }
    }
}
